name: Generate Pac-Man contribution graph

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Pac-Man contribution graph
        uses: yoshi389111/github-profile-pacman-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Update Pac-Man graph" || echo "No changes to commit"
          git push
          
